
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.25.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace Zensurrechner_Console {
    using System;
    using Terminal.Gui;
    
    
    public partial class addnoten : Terminal.Gui.Dialog {
        
        private Terminal.Gui.ColorScheme blueOnBlack;
        
        private Terminal.Gui.ColorScheme tgDefault;
        
        private Terminal.Gui.ColorScheme greyOnBlack;
        
        private Terminal.Gui.Label label;
        
        private Terminal.Gui.Label label16;
        
        private Terminal.Gui.Label label2;
        
        private Terminal.Gui.TextField class_input;
        
        private Terminal.Gui.Label label5;
        
        private Terminal.Gui.Label labelSummeNoten;
        
        private Terminal.Gui.Label label7;
        
        private Terminal.Gui.Label note1output;
        
        private Terminal.Gui.Label label9;
        
        private Terminal.Gui.Label note2output;
        
        private Terminal.Gui.Label label92;
        
        private Terminal.Gui.Label note3output;
        
        private Terminal.Gui.Label label3;
        
        private Terminal.Gui.Label label93;
        
        private Terminal.Gui.Label note4output;
        
        private Terminal.Gui.Label label94;
        
        private Terminal.Gui.Label note5output;
        
        private Terminal.Gui.TextField points_input;
        
        private Terminal.Gui.Label label95;
        
        private Terminal.Gui.Label note6output;
        
        private Terminal.Gui.Label label96;
        
        private Terminal.Gui.Label durchschnittOutput;
        
        private Terminal.Gui.Label label4;
        
        private Terminal.Gui.Button solve_btn;
        
        private Terminal.Gui.Button save_btn;
        
        private Terminal.Gui.Button close_btn;
        
        private void InitializeComponent() {
            this.close_btn = new Terminal.Gui.Button();
            this.save_btn = new Terminal.Gui.Button();
            this.solve_btn = new Terminal.Gui.Button();
            this.label4 = new Terminal.Gui.Label();
            this.durchschnittOutput = new Terminal.Gui.Label();
            this.label96 = new Terminal.Gui.Label();
            this.note6output = new Terminal.Gui.Label();
            this.label95 = new Terminal.Gui.Label();
            this.points_input = new Terminal.Gui.TextField();
            this.note5output = new Terminal.Gui.Label();
            this.label94 = new Terminal.Gui.Label();
            this.note4output = new Terminal.Gui.Label();
            this.label93 = new Terminal.Gui.Label();
            this.label3 = new Terminal.Gui.Label();
            this.note3output = new Terminal.Gui.Label();
            this.label92 = new Terminal.Gui.Label();
            this.note2output = new Terminal.Gui.Label();
            this.label9 = new Terminal.Gui.Label();
            this.note1output = new Terminal.Gui.Label();
            this.label7 = new Terminal.Gui.Label();
            this.labelSummeNoten = new Terminal.Gui.Label();
            this.label5 = new Terminal.Gui.Label();
            this.class_input = new Terminal.Gui.TextField();
            this.label2 = new Terminal.Gui.Label();
            this.label16 = new Terminal.Gui.Label();
            this.label = new Terminal.Gui.Label();
            this.blueOnBlack = new Terminal.Gui.ColorScheme();
            this.blueOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightBlue, Terminal.Gui.Color.Black);
            this.blueOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Cyan, Terminal.Gui.Color.Black);
            this.blueOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightBlue, Terminal.Gui.Color.BrightYellow);
            this.blueOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Cyan, Terminal.Gui.Color.BrightYellow);
            this.blueOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Gray, Terminal.Gui.Color.Black);
            this.tgDefault = new Terminal.Gui.ColorScheme();
            this.tgDefault.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Blue);
            this.tgDefault.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightCyan, Terminal.Gui.Color.Blue);
            this.tgDefault.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.Gray);
            this.tgDefault.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightBlue, Terminal.Gui.Color.Gray);
            this.tgDefault.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Brown, Terminal.Gui.Color.Blue);
            this.greyOnBlack = new Terminal.Gui.ColorScheme();
            this.greyOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.greyOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.greyOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.DarkGray);
            this.greyOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.DarkGray);
            this.greyOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.Width = Dim.Percent(85f);
            this.Height = Dim.Percent(85f);
            this.X = Pos.Center();
            this.Y = Pos.Center();
            this.Visible = true;
            this.Modal = true;
            this.IsMdiContainer = false;
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.Effect3D = true;
            this.Border.Effect3DBrush = null;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "Hinzufügen einer Note";
            this.label.Width = 4;
            this.label.Height = 1;
            this.label.X = Pos.Center();
            this.label.Y = 0;
            this.label.Visible = false;
            this.label.Data = "label";
            this.label.Text = "Hinzufügen einer Note";
            this.label.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.Add(this.label);
            this.label16.Width = 4;
            this.label16.Height = 1;
            this.label16.X = 13;
            this.label16.Y = 14;
            this.label16.Visible = true;
            this.label16.Data = "label16";
            this.label16.Text = "Statistik";
            this.label16.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label16);
            this.label2.Width = 4;
            this.label2.Height = 1;
            this.label2.X = Pos.Center();
            this.label2.Y = Pos.Center() - 5;
            this.label2.Visible = true;
            this.label2.Data = "label2";
            this.label2.Text = "Klassennamen eingeben:";
            this.label2.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label2);
            this.class_input.Width = 10;
            this.class_input.Height = 1;
            this.class_input.X = Pos.Center();
            this.class_input.Y = Pos.Bottom(label2) + 1;
            this.class_input.Visible = true;
            this.class_input.Secret = false;
            this.class_input.Data = "class_input";
            this.class_input.Text = "";
            this.class_input.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.class_input);
            this.label5.Width = 4;
            this.label5.Height = 1;
            this.label5.X = 2;
            this.label5.Y = 18;
            this.label5.Visible = true;
            this.label5.Data = "label5";
            this.label5.Text = "Anzahl Noten:";
            this.label5.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label5);
            this.labelSummeNoten.Width = 4;
            this.labelSummeNoten.Height = 1;
            this.labelSummeNoten.X = 18;
            this.labelSummeNoten.Y = 18;
            this.labelSummeNoten.Visible = true;
            this.labelSummeNoten.Data = "labelSummeNoten";
            this.labelSummeNoten.Text = "0";
            this.labelSummeNoten.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.labelSummeNoten);
            this.label7.Width = 4;
            this.label7.Height = 1;
            this.label7.X = 8;
            this.label7.Y = 20;
            this.label7.Visible = true;
            this.label7.Data = "label7";
            this.label7.Text = "Note 1:";
            this.label7.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label7);
            this.note1output.Width = 4;
            this.note1output.Height = 1;
            this.note1output.X = 18;
            this.note1output.Y = 20;
            this.note1output.Visible = true;
            this.note1output.Data = "note1output";
            this.note1output.Text = "0";
            this.note1output.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.note1output);
            this.label9.Width = 4;
            this.label9.Height = 1;
            this.label9.X = 8;
            this.label9.Y = 21;
            this.label9.Visible = true;
            this.label9.Data = "label9";
            this.label9.Text = "Note 2:";
            this.label9.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label9);
            this.note2output.Width = 4;
            this.note2output.Height = 1;
            this.note2output.X = 18;
            this.note2output.Y = 21;
            this.note2output.Visible = true;
            this.note2output.Data = "note2output";
            this.note2output.Text = "0";
            this.note2output.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.note2output);
            this.label92.Width = 4;
            this.label92.Height = 1;
            this.label92.X = 8;
            this.label92.Y = 22;
            this.label92.Visible = true;
            this.label92.Data = "label92";
            this.label92.Text = "Note 3:";
            this.label92.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label92);
            this.note3output.Width = 4;
            this.note3output.Height = 1;
            this.note3output.X = 18;
            this.note3output.Y = 22;
            this.note3output.Visible = true;
            this.note3output.Data = "note3output";
            this.note3output.Text = "0";
            this.note3output.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.note3output);
            this.label3.Width = 4;
            this.label3.Height = 1;
            this.label3.X = Pos.Center();
            this.label3.Y = Pos.Bottom(class_input) + 4;
            this.label3.Visible = true;
            this.label3.Data = "label3";
            this.label3.Text = "BE eingeben:";
            this.label3.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label3);
            this.label93.Width = 4;
            this.label93.Height = 1;
            this.label93.X = 8;
            this.label93.Y = 23;
            this.label93.Visible = true;
            this.label93.Data = "label93";
            this.label93.Text = "Note 4:";
            this.label93.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label93);
            this.note4output.Width = 4;
            this.note4output.Height = 1;
            this.note4output.X = 18;
            this.note4output.Y = 23;
            this.note4output.Visible = true;
            this.note4output.Data = "note4output";
            this.note4output.Text = "0";
            this.note4output.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.note4output);
            this.label94.Width = 4;
            this.label94.Height = 1;
            this.label94.X = 8;
            this.label94.Y = 24;
            this.label94.Visible = true;
            this.label94.Data = "label94";
            this.label94.Text = "Note 5:";
            this.label94.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label94);
            this.note5output.Width = 4;
            this.note5output.Height = 1;
            this.note5output.X = 18;
            this.note5output.Y = 24;
            this.note5output.Visible = true;
            this.note5output.Data = "note5output";
            this.note5output.Text = "0";
            this.note5output.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.note5output);
            this.points_input.Width = 10;
            this.points_input.Height = 1;
            this.points_input.X = Pos.Center();
            this.points_input.Y = Pos.Bottom(label3) + 1;
            this.points_input.Visible = true;
            this.points_input.Secret = false;
            this.points_input.Data = "points_input";
            this.points_input.Text = "";
            this.points_input.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.Add(this.points_input);
            this.label95.Width = 4;
            this.label95.Height = 1;
            this.label95.X = 8;
            this.label95.Y = 25;
            this.label95.Visible = true;
            this.label95.Data = "label95";
            this.label95.Text = "Note 6:";
            this.label95.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label95);
            this.note6output.Width = 4;
            this.note6output.Height = 1;
            this.note6output.X = 18;
            this.note6output.Y = 25;
            this.note6output.Visible = true;
            this.note6output.Data = "note6output";
            this.note6output.Text = "0";
            this.note6output.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.note6output);
            this.label96.Width = 4;
            this.label96.Height = 1;
            this.label96.X = 2;
            this.label96.Y = 27;
            this.label96.Visible = true;
            this.label96.Data = "label96";
            this.label96.Text = "Durchschnitt:";
            this.label96.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label96);
            this.durchschnittOutput.Width = 4;
            this.durchschnittOutput.Height = 1;
            this.durchschnittOutput.X = 18;
            this.durchschnittOutput.Y = 27;
            this.durchschnittOutput.Visible = true;
            this.durchschnittOutput.Data = "durchschnittOutput";
            this.durchschnittOutput.Text = "0";
            this.durchschnittOutput.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.durchschnittOutput);
            this.label4.Width = 4;
            this.label4.Height = 1;
            this.label4.X = Pos.Center();
            this.label4.Y = Pos.Bottom(points_input) + 2;
            this.label4.Visible = true;
            this.label4.Data = "label4";
            this.label4.Text = "Max. BE 10";
            this.label4.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.Add(this.label4);
            this.solve_btn.Width = 11;
            this.solve_btn.Height = 1;
            this.solve_btn.X = Pos.Center();
            this.solve_btn.Y = Pos.Bottom(label4) + 8;
            this.solve_btn.Visible = true;
            this.solve_btn.Data = "solve_btn";
            this.solve_btn.Text = "Rechnen";
            this.solve_btn.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.solve_btn.IsDefault = false;
            this.Add(this.solve_btn);
            this.save_btn.Width = 12;
            this.save_btn.Height = 1;
            this.save_btn.X = Pos.Center();
            this.save_btn.Y = 38;
            this.save_btn.Visible = true;
            this.save_btn.ColorScheme = this.tgDefault;
            this.save_btn.Data = "save_btn";
            this.save_btn.Text = "Speicher";
            this.save_btn.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.save_btn.IsDefault = false;
            this.Add(this.save_btn);
            this.close_btn.Width = 13;
            this.close_btn.Height = 1;
            this.close_btn.X = Pos.Center();
            this.close_btn.Y = Pos.Bottom(solve_btn) + 2;
            this.close_btn.Visible = true;
            this.close_btn.Data = "close_btn";
            this.close_btn.Text = "Schließen";
            this.close_btn.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.close_btn.IsDefault = false;
            this.Add(this.close_btn);
        }
    }
}
