
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.25.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace Zensurrechner_Console {
    using System;
    using Terminal.Gui;
    
    
    public partial class datalists : Terminal.Gui.Dialog {
        
        private Terminal.Gui.Button loadBtn;
        
        private Terminal.Gui.Label load_resualt;
        
        private Terminal.Gui.Button exitBtn;
        
        private void InitializeComponent() {
            this.exitBtn = new Terminal.Gui.Button();
            this.load_resualt = new Terminal.Gui.Label();
            this.loadBtn = new Terminal.Gui.Button();
            this.Width = Dim.Percent(85f);
            this.Height = Dim.Percent(85f);
            this.X = Pos.Center();
            this.Y = Pos.Center();
            this.Visible = true;
            this.Modal = true;
            this.IsMdiContainer = false;
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.Effect3D = true;
            this.Border.Effect3DBrush = null;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "Auflistung der Klassen";
            this.loadBtn.Width = 8;
            this.loadBtn.Height = 1;
            this.loadBtn.X = Pos.Center();
            this.loadBtn.Y = 0;
            this.loadBtn.Visible = true;
            this.loadBtn.Data = "loadBtn";
            this.loadBtn.Text = "Load";
            this.loadBtn.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.loadBtn.IsDefault = false;
            this.Add(this.loadBtn);
            this.load_resualt.Width = 4;
            this.load_resualt.Height = 1;
            this.load_resualt.X = Pos.Center();
            this.load_resualt.Y = Pos.Center() - 6;
            this.load_resualt.Visible = true;
            this.load_resualt.Data = "load_resualt";
            this.load_resualt.Text = "noch nichts geladen.";
            this.load_resualt.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.load_resualt);
            this.exitBtn.Width = 8;
            this.exitBtn.Height = 1;
            this.exitBtn.X = Pos.Center();
            this.exitBtn.Y = Pos.Bottom(load_resualt) + 12;
            this.exitBtn.Visible = true;
            this.exitBtn.Data = "exitBtn";
            this.exitBtn.Text = "Exit";
            this.exitBtn.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.exitBtn.IsDefault = false;
            this.Add(this.exitBtn);
        }
    }
}
