
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.25.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace Zensurrechner_Console {
    using System.IO;
    using System.Text.Json;
    using System.Threading.Tasks;
    using System;
    using Terminal.Gui;
    
    
    public partial class datalists {
        
        public datalists() {
            InitializeComponent();

            loadBtn.Clicked += async () =>
            {
                
                MessageBox.Query("Auflistung aller Klassen erfolgt.\nBitte warten...", "Wait", "OK");
                string fileName = "notensumme.json";
                using FileStream openStream = File.OpenRead(fileName);
                NotenSpeicherung? notenSpeicherung =
                await JsonSerializer.DeserializeAsync<NotenSpeicherung>(openStream);
               
                string liststring;
                Console.WriteLine("Auflistung:\n");
                liststring = ("Auflistung:\n");
                load_resualt.Text = liststring;
                await Task.Delay(2000);
                Console.WriteLine($"Klassenname: {notenSpeicherung.Klassenname}\nSumme aler Notenwerte: {notenSpeicherung.SummeAllerNoten}\nAnzahl an der Note 1: {notenSpeicherung.AnzahlAnNote1}\nAnzahl an der Note 2: {notenSpeicherung.AnzahlAnNote2}\nAnzahl an der Note 3: {notenSpeicherung.AnzahlAnNote3}\nAnzahl an der Note 4: {notenSpeicherung.AnzahlAnNote4}\nAnzahl an der Note 5: {notenSpeicherung.AnzahlAnNote5}\nAnzahl an der Note 6: {notenSpeicherung.AnzahlAnNote6}\nAnzahl aller Noten: {notenSpeicherung.AnzahlAnNoten}\nDurchschnitt: {notenSpeicherung.Durchschnitt}");
                liststring = ($"Klassenname: {notenSpeicherung.Klassenname}\nSumme aler Notenwerte: {notenSpeicherung.SummeAllerNoten}\nAnzahl an der Note 1: {notenSpeicherung.AnzahlAnNote1}\nAnzahl an der Note 2: {notenSpeicherung.AnzahlAnNote2}\nAnzahl an der Note 3: {notenSpeicherung.AnzahlAnNote3}\nAnzahl an der Note 4: {notenSpeicherung.AnzahlAnNote4}\nAnzahl an der Note 5: {notenSpeicherung.AnzahlAnNote5}\nAnzahl an der Note 6: {notenSpeicherung.AnzahlAnNote6}\nAnzahl aller Noten: {notenSpeicherung.AnzahlAnNoten}\nDurchschnitt: {notenSpeicherung.Durchschnitt}");
                load_resualt.Text = liststring;
                openStream.Close();
            };
            exitBtn.Clicked += () => Application.RequestStop();

        }
    }
}
