using System.Threading.Tasks;
using System;
using Terminal.Gui;
using System.IO;
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.25.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace Zensurrechner_Console {
    
    
    
    public partial class Programm_sec {
        
        public Programm_sec() {
            InitializeComponent();
            
            pointadding_btn.Clicked += () => openaddmenu();

            list_btn.Clicked += () => openlistmenu();
            resetAll_btn.Clicked += async () => {
                string fileName = "notensumme.json";
                File.Delete(fileName);
                Console.Clear();
                Console.WriteLine("Console cleared");
                await Task.Delay(1000);
                MessageBox.Query("Reset", "Alles zurück gesetzt", "OK");

            };
        }
        public void openaddmenu()
        {
            var dialog = new addnoten();
            Application.Run(dialog);
        }
        public void openlistmenu()
        {
            var dialog = new datalists();
            Application.Run(dialog);
        }
    }
}
